---
- name: Validate vs required parameters
  assert:
    that:
      - vs_address is defined
      - vs_protocol is defined
      - vs_port is defined
      - vs_vlans is defined

- name: Create virtual server
  bigip_virtual_server:
    state: present
    partition: "{{ partition }}"
    name: "{{ vs_name }}_{{ vs_protocol }}{{ vs_port }}_vs"
    destination: "{{ vs_address }}"
    port: "{{ vs_port }}"
    ip_protocol: "{{ vs_protocol }}"
    enabled_vlans: "{{ (vs_vlans | split(',')) }}"
    snat: Automap
    pool: "{{ pool_name | default(omit) }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: true
      transport: rest
      validate_certs: "{{ provider_validate_certs }}"
  register: _create_vs_result

- name: Display created virtual server
  debug:
    msg: "{{ _create_vs_result }}"
