---
- name: Remove virtual server
  bigip_virtual_server:
    state: absent
    partition: "{{ partition }}"
    name: "{{ _vs_name }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: true
      transport: rest
      validate_certs: "{{ provider_validate_certs }}"
  register: _remove_vs_result

- name: Display remove virtual server result
  debug:
    msg: "{{ _remove_vs_result }}"